### ISSUE TITLE
Misclassification of muscle groups for certain exercises  

### ISSUE THREAD

**Issue by cbragg1** [labsansis/workout-stats#35]
I really like this idea and appreciate the effort into it. It's way better than the Garmin layout.

I've noticed that in the training volume tab, some exercises aren't being classified into muscle groups correctly. I've logged several bench press exercises, which show up correctly in the other tabs, but under exercise volume, it shows as 0 chest or arm exercises. A feature where you could see a breakdown of what specific exercise contributed to the total exercise volume for each muscle group would be really useful.

**Comment by labsansis** [comment]
Ah interesting! I'm actually using Garmin's own data for determining exercise muscle groups. Bench press should absolutely be classified under chest, not sure what's going on there.

Can you check that the relevant workout falls within the time window configured in the training volume section? If it's still showing up as zero chest volume, if you give me permission to rummage through your workout data I can look into this at some point soon.

If you want to discuss this more privately feel free to write to hi@workout.love

**Comment by cbragg1** [comment]
Even when set to "since start" in the training volume window, it still shows zero chest volume. I can email you the workout log. Thanks.

**Comment by labsansis** [comment]
Thanks for the data, that made it easy to identify the issue - it's to do with how Garmin stores the exercise identifiers in some edge cases. I've now fixed that and also added the breakdown of muscle group volume by exercise (have to click on the relevant muscle group bar in the chart).

Two final points here:

1. You had a bunch of sets in your workouts with zero reps each. Can you shed some light on how these came about? These zero-rep sets currently count towards the training volume, which I suspect is not what you'd expect in your case. I don't want to flat out exclude them as there may be cases where that's the wrong call - will prob add an account-specific setting for it.
2. I saw that your exercise weights were probably logged in lbs: FYI there's now an account setting you can change to use lbs on the UI!

**Comment by cbragg1** [comment]
Yes, the sets with zero reps were because they were warmup sets with no rest in between. Garmin does not allow input of reps and weight on sets with no rest during the workout. I switched away from including warmup sets in the workout and will just do them on my own so as not to throw off the workout volume. Thanks!

**Comment by labsansis** [comment]
Ah I see, thanks for the context. The warmup use case makes sense. I changed the UI to exclude zero-rep sets from training volume by default and added a toggle to include them if anyone wants to. Closing this.
