### ISSUE TITLE
Switch between kg and lbs?

### ISSUE THREAD

**Issue by cbragg1** [labsansis/workout-stats#36]
Great work on this.

Could you add the ability to switch between lbs and kg for the various stats?

Thanks!

**Comment by labsansis** [comment]
Hi! Thanks for creating the ticket.

I looked into this a bit and decided to follow the same approach as Garmin does under the hood: all weights are stored in grams and converted to whatever unit you have configured in your account when displayed.

I added a setting in the Account section to switch between metric & imperial.
